# Generated by Django 4.0.1 on 2022-07-23 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartmodels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feedbackmodel',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbackmodels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='widlistmodel',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='widlistmodels', to=settings.AUTH_USER_MODEL),
        ),
    ]
