# Generated by Django 4.0.1 on 2022-08-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_alter_cartmodel_owner_alter_feedbackmodel_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartmodel',
            name='order',
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='cart_count',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='image',
            field=models.ImageField(default=1, upload_to='CartModelImage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='price',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='title',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='owner',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
