# Generated by Django 4.0.1 on 2022-08-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_remove_cartmodel_order_cartmodel_cart_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='cart_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
