# Generated by Django 4.0.1 on 2022-08-02 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0003_productmodel_newprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='count',
            new_name='product_count',
        ),
    ]
