# Generated by Django 4.0.1 on 2022-08-06 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0004_rename_count_productmodel_product_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likemodel',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='likemodel',
            name='like',
        ),
    ]
