# Generated by Django 4.0.1 on 2022-08-07 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0007_alter_productmodel_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='productmodel',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homeapp.color_model'),
        ),
    ]
