# Generated by Django 4.0.1 on 2022-08-10 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0008_color_model_productmodel_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
