# Generated by Django 4.0.1 on 2022-08-10 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0009_alter_productmodel_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colormodel',
            old_name='code',
            new_name='color',
        ),
        migrations.RemoveField(
            model_name='colormodel',
            name='name',
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homeapp.colormodel'),
        ),
        migrations.DeleteModel(
            name='Color_Model',
        ),
    ]
